/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
public interface ParserConstants {

  int EOF = 0;
  int AND = 6;
  int OR = 7;
  int IMPLICATION = 8;
  int BICONDITIONAL = 9;
  int NEGATION = 10;
  int FORALL = 11;
  int EXISTS = 12;
  int LEFT_PAREN = 13;
  int RIGHT_PAREN = 14;
  int COMMA = 15;
  int EQUAL = 16;
  int CAPITAL_LETTER = 17;
  int SMALL_LETTER = 18;
  int DIGIT = 19;
  int SMALL_ID = 20;
  int CAPITAL_ID = 21;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"&&\"",
    "\"||\"",
    "\"->\"",
    "\"<->\"",
    "\"~\"",
    "\"forall\"",
    "\"exists\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "<CAPITAL_LETTER>",
    "<SMALL_LETTER>",
    "<DIGIT>",
    "<SMALL_ID>",
    "<CAPITAL_ID>",
  };

}
