package br.mia.parser;
/* Generated By:JJTree: Do not edit this line. .\ParserTreeConstants.java */

public interface ParserTreeConstants
{
  public int JJTNEGATION = 0;
  public int JJTVAR = 1;
  public int JJT_CONST = 2;
  public int JJTPARAM = 3;
  public int JJTPARAMLIST = 4;
  public int JJTFUNC = 5;
  public int JJTPRED = 6;
  public int JJTCONNECTIVE = 7;
  public int JJTQUANTIFIER = 8;
  public int JJTWFF = 9;
  public int JJTWFFLIST = 10;
  public int JJTSTART = 11;


  public String[] jjtNodeName = {
    "negation",
    "var",
    "_const",
    "param",
    "paramList",
    "func",
    "pred",
    "connective",
    "quantifier",
    "wff",
    "wffList",
    "start",
  };
}
